[package]
name = "muc-student-winui"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "MUC-student"
path = "src/main.rs"

[dependencies]
muc-student-core = { path = "../src-core" }
chrono = { version = "0.4", features = ["serde"] }
dirs = "6"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "time"] }
winio-winui3 = { version = "0.4.0", features = [
    "native",
    "UI_Composition",
    "UI_Dispatching",
    "UI_Text",
    "UI_Windowing",
    "UI_Xaml",
    "UI_Xaml_Controls",
    "UI_Xaml_Controls_Primitives",
    "UI_Xaml_Media",
] }
windows = { version = "0.62.2", features = [
    "Foundation",
    "Foundation_Collections",
    "UI",
    "UI_Text",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Security",
    "Win32_Storage_Packaging_Appx",
    "Win32_System_Com",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_System_Registry",
    "Win32_System_WinRT",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
] }
windows-core = "0.62.2"
