name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  checks:
    runs-on: windows-latest

    steps:
      - name: Pull repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Format workspace
        run: cargo fmt --check

      - name: Check workspace
        run: cargo check

      - name: Test workspace
        run: cargo test
